output "smtp_host" {
  description = "OCI Email Delivery SMTP endpoint for the configured region."
  value       = "smtp.email.${var.region}.oci.oraclecloud.com"
}

output "smtp_user" {
  description = "SMTP username generated by OCI for the IAM user SMTP credential."
  value       = oci_identity_smtp_credential._.username
}

output "smtp_password" {
  description = "SMTP password generated by OCI for the IAM user SMTP credential."
  value       = oci_identity_smtp_credential._.password
  sensitive   = true
}

output "smtp_sender_email" {
  description = "Approved sender email address registered in OCI Email Delivery."
  value       = oci_email_sender._.email_address
}

output "smtp_sender_state" {
  description = "Current verification state of the approved sender."
  value       = oci_email_sender._.state
}
